### PR TITLE
Test to enable simple links between containers and child records

### PR DESCRIPTION
**Pull request by carlonim**
I have tried to enable containers to display some sort of hierarchy between the resources. Links are based on the AC-control numbers (= local field MARC 009 in our catalogue). The link is established between the Solr fields `is_hierarchy_id` (in the **parent** resource) and `hierarchy_parent_id` (in the **child** resource). Containers were enabled in the `config.ini` file and componentParts in the `RecordTabs.ini` file.
It's still very tentative and buggy:

- I still can't display the link to the parent resource in the child resource (links are displayed just one way, from parent to child).
- I mapped the field `container_title` (which apparently is required to display links to containers) to `245a`, which might not be the right solution, but was a temporary escamotage to make it work
- **And most importantly**: If you click on the link to display child resources, you won't find any, because Solr queries to find child resources are built by searching the MMS ID (and not the AC-control number) in the `hierarchy_parent_id` field.

👉 A related branch, with the same name, is available in the repo for AkSearchSolr, where the **mapping** is to be found.

### CODE REVIEW

**Comment by zozlak** [comment]
## context

We have many different primary keys in our MARC records: Alma's MMS id (indexed in the `id` solr field) as well as many others (indexed as a collection of values in the `ctrlnum` solr field). The problem is different MARC fields use different identifiers in different fields to denote other records, e.g. in this case the AC identifiers are used to denoted child-parent relationship between records. Similarly it turns out the vufind/aksearch code allows to use many kinds of identifiers in some places (e.g. it's possible to open the record page with `{baseUrl}/{AC identifier}`) but doesn't in others (e.g. for displaying hierarchies - see [vufind's wiki](https://vufind.org/wiki/indexing:hierarchies_and_collections)).

A sibling PR for the aksearch solr is [here](https://github.com/acdh-oeaw/AkSearchWeb/pull/3).

## solutions

There are basically two solutions:

1. Postprocess the solr index after every import (or preprocessing MARC XML records before the import) assuring fields used for describing the hierarchy follow current [vufind/aksearch code expectations](https://vufind.org/wiki/indexing:hierarchies_and_collections). Here it would mean mapping some solr field values from their current AC identifier values to corresponding MMS id values. It's worth noting post/pre processing requires whole index of the AC-MMS id mappings to be available.
2. Adjust the vufind/aksearch code responsible for hierarchy visualization in a way it can work with any identifier in the `ctrlnum` field and not only with the one in the `id` field.

I need to check which one sounds more promising. This requires looking into the vufind/aksearch code. Should do it by the end of the week.

## side questions

@ctot-nondef , @carlonim - are you aware of other places/features where we can have the same problem (vufind/aksearch expect particular id type to denote a given relation between records while our MARC records use different identifier type)?

**Comment by zozlak** [comment]
@carlonim - which features out of the ones described in the [vufind's wiki](https://vufind.org/wiki/indexing:hierarchies_and_collections) we need? (full multilevel trees, flat parent-child, collection views)
Do we have a corresponding Redmine ticket?

**Comment by ctot-nondef** [comment]
@zozlak regarding your questions about other scenarios where the duality of MMS-ID and AC-Numbers occur in one field: it actually also came up in field 773w (LKR - links) , BAS:IS is currently working on finding out wether this is something they can fix (because it is not the standard), I'll let you know once I know

regarding the identifiers in the URL, this is actually configured here: https://github.com/acdh-oeaw/AkSearchWeb/blob/d1bfaac38f069ee93903849fb96315f86ecd835f/local/config/vufind/searches.ini#L756

**Comment by carlonim** [comment]
> @carlonim - which features out of the ones described in the [vufind's wiki](https://vufind.org/wiki/indexing:hierarchies_and_collections) we need? (full multilevel trees, flat parent-child, collection views)
> Do we have a corresponding Redmine ticket?

@zozlak For the moment, just "Simple Links Between Containers and Child Records". It's the most basic feature to display hierarchies but it should be enough for most (or even all) of our needs. I have never managed to make collections work, but maybe if we change how identifiers are used to build collections, they might also work eventually.
(Sorry for the delay, I was busy with Tool Gallery + DH research JF 😅)

**Comment by carlonim** [comment]
@zozlak Almost forgot: Redmine ticket [#19487](https://redmine.acdh.oeaw.ac.at/issues/19487)

**Comment by zozlak** [comment]
> BAS:IS is currently working on finding out wether this is something they can fix (because it is not the standard)

That would be the easiest solution for us :-D 
Should we wait or should we try to dig on our side as well?
In the latter case I would need us to reshape this pull request in a way I can easily setup an instance (on my laptop) which has a few sample resources forming the hierarchy and using Massimiliano's updated mappings. This will allow me to experiment with the vufind/aksearch code. For that I would need Massimiliano to get rid of his-computer-specific code like absolute mounts in the `docker-compose.yaml` :-) (I think everything will work without them, just the docker image build will be required).

**Comment by carlonim** [comment]
@zozlak I've just pushed a further commit, where I've replaced absolute paths with relative ones -- they presuppose that the `AkSearchWeb` and `AkSearchSolr` directories have the same parent directory, but if you prefer a different setup just let me know 😉
I've also turned on debug mode in `local/config/vufind/config.ini`, so you can see what kind of requests are sent to Solr.
I would recommend to import the `select1000.xml` dataset in the `sample` directory of the AkSearchSolr repo. This is the only test dataset where records for _both_ parent and child resources are present.
Here is a list of child resources and their respective parents (the same as https://redmine.acdh.oeaw.ac.at/issues/19487#note-7):

**(child -> parent)**
AC07012776 -> AC05778895
AC07020371 -> AC05778895
AC07020481 -> AC05778895
AC04272904 -> AC01732410
AC08791228 -> AC00020422
AC01320373 -> AC01320366

So, for example, if you go to http://localhost/vufind/Record/AC05778895 you'll find a resource with three child resources. There is a field in the record view as well as a tab that signals the presence of the three 'Contents/pieces', but if you click on the link you'll get an error message "No results!", because Solr looks for the MMS ID of the parent resource in the field `hierarchy_parent_id`.

**Comment by zozlak** [comment]
Ok, getting parent->child work won't be too difficult.

The link is generated trough `VuFind/src/VuFind/View/Helper/Root/RecordLink::getChildRecordSearchUrl()` which reads the parent id using `{recordDriverClass}::getUniqueID()`, so it's enough to implement `aksearchExt\SolrMarc::getUniqueID()` (`aksearchExt\SolrMarc` is our driver class being extension of `AkSearch\RecordDriver\SolrMarc`) in a way it can distinguish calls from `VuFind/src/VuFind/View/Helper/Root/RecordLink::getChildRecordSearchUrl()` from other ones and serve `$this->getMarcRecord()->getField(9)->getData();` (the AC id) when needed.

As call stack introspection in PHP is cheap (`debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2)` takes below 3 us on my laptop) it shouldn't slow down page rendering (even if `{recordDriverClass}::getUniqueID()` is called 100 times during the render it will add only 3 ms in total).

One more thing to inspect and fix for the parent->children is where the number of child records comes from.

**Comment by zozlak** [comment]
I've just published [AkSearchExt 1.2.1](https://github.com/acdh-oeaw/AkSearchExtend/releases/tag/1.2.1) and set the version required by the AkSearchWeb to 1.2.1 as well.

The good thing is it seemed to be enough to make the parent->children direction work on production (see e.g. https://oeaw-resources.acdh-dev.oeaw.ac.at/vufind/Record/AC05778895). I guess you must have already reindexed the production version in a way `hierarchy_parent_id` solr field was filled in (otherwise it would rather not work :-) ) and it looks like changes proposed by @carlonim here (which go down to the `local/config/vufind/RecordTabs.ini` - everything else is deployment-related) aren't really needed. Please:

* Check if it works as expected.
* Check if changes proposed by Massimiliano here (basically `local/config/vufind/RecordTabs.ini`) introduce something which doesn't work on production at the moment.

I'm starting to investigate the child->parent direction.

**Comment by zozlak** [comment]
With child->parent it's a little more complex because the AkSearch completely overridden the child to parent linking. To make it work in a way it's describe in the [fuvind wiki](https://vufind.org/wiki/indexing:hierarchies_and_collections#simple_links_between_containers_and_child_records) we must:

* Find all the templates where AkSearch replaced the standard parent display with its custom methods.  
  The good starting point might be `grep -Rn getContainerTitle {vufinddir}/themes/bootstrap3` (the default theme which should be in line with the vufind's wiki) and comparing corresponding templates with AkSearch ones and/or our ones - see examples below. Funnily none of templates found that way corresponds to a single record view. In fact even `grep -Rn --color getContainer {vufinddir}/themes/*/templates/RecordTab` (searching all templates responsible for a single record rendering) fetches no results at all. Do we have any example of a vufind/aksearch-based service showing child->parent link in this view?
  * `themes/AkSearch/templates/RecordDriver/DefaultRecord/list-entry.phtml` vs `themes/AcdhchTheme/templates/RecordDriver/DefaultRecord/list-entry.phtml` (favorite records list element template).
  * `themes/bootstrap3/templates/RecordDriver/Pazpar2/result-list.phtml` vs `themes/AcdhchTheme/templates/RecordDriver/DefaultRecord/result-list.phtml` (search results list element template). In this case AkSearch developer was nice and only commented out the original fuvind's code - [see here](https://github.com/acdh-oeaw/AkSearchAcdhTheme/blob/master/templates/RecordDriver/DefaultRecord/result-list.phtml#L81-L93.
* Restore original record driver class methods being used in the templates from the previous point (for sure `getContainerTitle()`, maybe something else as well - we must note down what's called in the templates and check if it's not overriden by the AkSearch). As original vufind implementations suite us well this will go down to adding something like
  ```php
      /**
     * Restores the getContainerTitle() to the VuFind original one
     * (AkSearch provided own version based on custom fields)
     */
    public function getContainerTitle() {
        return \VuFind\RecordDriver\DefaultRecord::getContainerTitle();
    }
  ```
  in our `SolrMarc` [class](https://github.com/acdh-oeaw/AkSearchExtend/blob/master/src/aksearchExt/SolrMarc.php).

**Comment by ctot-nondef** [comment]
sample link for hierarchies from new aksearch: https://aksearch.arbeiterkammer.at/Record/990004633210203343#parts
from our old version: https://www.oeaw.ac.at/resources/Record/990000391670504498#multivolumeworks

**Comment by zozlak** [comment]
The "Contents/Pieces" tab in the single record view suffered from the same problem as the "Contents/Pieces" link - was using the main id instead of the AC one - and required exactly same tuning in our `aksearchExt\SolrMarc::getUniqueID()`.

As suggested by @carlonim  to make the "Contents/Pieces" tab visibile we need a little tuned `RecordTabs.ini`. I decided to set it up in the most explicit way ([see here](https://github.com/acdh-oeaw/AkSearchWeb/commit/a34e3f907df08b1f031564a2f06be282a1cff435)) so we only include what's important for our service skipping all the unneeded config and so it leads us directly to the correct place in the code (our `aksearchExt\SolrMarc` class).

The list is now being displayed properly in a "vufind default way" - using the `container_title` solr field of children and limiting the list to 100 positions (with a link to all) - see [how it works on production](https://oeaw-resources.acdh-dev.oeaw.ac.at/vufind/Record/990000391670504498#componentparts).

**Comment by zozlak** [comment]
And we have the child->parent link as well, e.g. [here](https://oeaw-resources.acdh-dev.oeaw.ac.at/vufind/Record/990003099570504498). It combines better AkSearch template (using id-based linking instead of title string-based one implemented in vanilla VuFing) with nice and simple vanilla VuFind's [hierarchy-related solr fields](https://vufind.org/wiki/indexing:hierarchies_and_collections).

In the meantime I added missing php-xsl module to the runtime environment so the "MARC" tab in the record view renders properly.

**Comment by zozlak** [comment]
@carlonim , @ctot-nondef - do we have a Redmine issue corresponding to this feature? (can't find anything matching in https://redmine.acdh.oeaw.ac.at/issues/17070)

**Comment by carlonim** [comment]
> @carlonim , @ctot-nondef - do we have a Redmine issue corresponding to this feature? (can't find anything matching in https://redmine.acdh.oeaw.ac.at/issues/17070)

https://redmine.acdh.oeaw.ac.at/issues/19487

**Pull request closed without merging**
